In [99]:
import pandas as pd
import numpy as np

In [100]:
file = ("LewistonID.xlsx")

In [120]:
df = pd.read_excel(file)
df.head(30)

,OBJECTID,Cartegraph,Criticalit,CurrentIns,CurrentI_1,CurrentI_2,CurrentI_3,CurrentI_4,Descriptio,From,...,ZipLeft,ZipRight,Zone,GISID,created_us,created_da,last_edite,last_edi_1,SHAPE_Leng,PASS
0,1.0,1451900 2,1.0,9037.0,NaN,NaN,0.0,NaN,Birch Dr - 19th St to EEOR 2,NaN,...,1.0,0.0,25.0,3071.0,NaN,NaT,gisadmin,2023-04-29,1028.346237,1.0
1,2.0,0122100,1.0,NaN,NaN,NaN,0.0,NaN,1st St - 2100 To 2200,NaN,...,2.0,0.0,25.0,3462.0,NaN,NaT,gisadmin,2023-04-22,534.780764,1.0
2,3.0,1041500,1.0,4304.0,NaN,NaN,0.0,NaN,21st St - 15th Ave To 16th Ave,NaN,...,2.0,0.0,35.0,2344.0,NaN,NaT,gisadmin,2023-04-06,379.435270,2.0
3,4.0,1041600,1.0,4305.0,NaN,NaN,0.0,NaN,21st St - 16th Ave To 17th Ave,NaN,...,2.0,0.0,35.0,2392.0,NaN,NaT,gisadmin,2023-04-06,381.350290,2.0
4,5.0,1851600,1.0,NaN,NaN,NaN,0.0,NaN,Grelle Ave - 16th St To 17th St,NaN,...,1.0,0.0,35.0,2966.0,NaN,NaT,gisadmin,2023-04-29,1325.264456,2.0
5,6.0,2420500 5,1.0,4328.0,NaN,NaN,0.0,NaN,Preston Ave - Nez Perce Grade To 6th St,NaN,...,2.0,0.0,35.0,3857.0,NaN,NaT,gisadmin,2023-04-28,324.411975,2.0
6,7.0,2420400 3,1.0,4321.0,NaN,NaN,0.0,NaN,Preston Ave - 4th St D To 5th St,NaN,...,2.0,0.0,25.0,3819.0,NaN,NaT,gisadmin,2023-04-27,668.458334,2.0
7,8.0,1130600 2,1.0,7820.0,NaN,NaN,0.0,NaN,24th St - Cassell St To 722,NaN,...,3.0,0.0,25.0,3712.0,NaN,NaT,gisadmin,2023-04-29,60.221475,1.0
8,9.0,0440200,1.0,NaN,NaN,NaN,0.0,NaN,8th Ave - Prospect Ave To 3rd St,NaN,...,3.0,0.0,25.0,1935.0,NaN,NaT,gisadmin,2023-04-28,325.138822,1.0
9,10.0,2360600 1,1.0,NaN,NaN,NaN,0.0,NaN,Park Ave - 6th St To 6th St C,NaN,...,1.0,0.0,25.0,3906.0,NaN,NaT,gisadmin,2023-04-29,500.318007,1.0
10,11.0,2921000,1.0,NaN,NaN,NaN,0.0,NaN,16th St - 10th Ave To 11th Ave,NaN,...,3.0,0.0,0.0,2098.0,NaN,NaT,gisadmin,2023-04-29,371.652485,1.0
11,12.0,2892600,1.0,NaN,NaN,NaN,0.0,NaN,Willow Dr - 2600 To 2700,NaN,...,3.0,0.0,25.0,2113.0,NaN,NaT,gisadmin,2023-04-29,240.805702,1.0
12,13.0,1901700 1,1.0,NaN,NaN,NaN,0.0,NaN,Hemlock Ave - 17th St To 17th St C,NaN,...,1.0,0.0,25.0,3310.0,NaN,NaT,gisadmin,2023-04-29,499.006891,1.0
13,14.0,1580800 1,1.0,8729.0,NaN,NaN,0.0,NaN,Cedar Ave - 8th St To 8th St C,NaN,...,1.0,0.0,25.0,3915.0,NaN,NaT,gisadmin,2023-04-29,505.843945,1.0
14,15.0,2680600 2,1.0,9329.0,NaN,NaN,0.0,NaN,Stewart Ave - 6th St B To 7th St,NaN,...,1.0,0.0,25.0,2641.0,NaN,NaT,gisadmin,2023-04-29,1000.407855,1.0
15,16.0,0812400,1.0,6284.0,NaN,NaN,0.0,NaN,14th StGr - 24th Ave To 2500,NaN,...,2.0,0.0,25.0,2559.0,NaN,NaT,gisadmin,2023-04-29,310.022717,2.0
16,17.0,2552600,1.0,NaN,NaN,NaN,0.0,NaN,Seaport Dr - 2600 To 2700,NaN,...,2.0,0.0,25.0,2681.0,NaN,NaT,gisadmin,2023-04-22,432.599800,1.0
17,18.0,1972100 1,1.0,NaN,NaN,NaN,0.0,NaN,Juniper Dr - Nez Perce Dr To 2800,NaN,...,1.0,0.0,25.0,3232.0,NaN,NaT,gisadmin,2023-04-29,941.301798,1.0
18,19.0,0551300,1.0,NaN,NaN,NaN,0.0,NaN,10th Ave - 13th St To 14th St,NaN,...,3.0,0.0,25.0,2054.0,NaN,NaT,gisadmin,2023-04-29,379.276922,1.0
19,20.0,1850800 2,1.0,9198.0,NaN,NaN,0.0,NaN,Grelle Ave - 8th St E To 9th St,NaN,...,1.0,0.0,25.0,2955.0,NaN,NaT,gisadmin,2023-04-29,503.719656,1.0
20,21.0,1851400,1.0,NaN,NaN,NaN,0.0,NaN,Grelle Ave - 14th St To 15th St,NaN,...,1.0,0.0,35.0,2963.0,NaN,NaT,gisadmin,2023-04-28,1320.759447,2.0
21,22.0,0933700 3,1.0,8447.0,NaN,NaN,0.0,NaN,18th St - Birch Ave To Birch Dr,NaN,...,1.0,0.0,25.0,3041.0,NaN,NaT,gisadmin,2023-04-29,329.268603,1.0
22,23.0,0343400 4,1.0,8273.0,NaN,NaN,0.0,NaN,6th St - Airway Dr To Burrell Ave,NaN,...,1.0,0.0,25.0,3849.0,NaN,NaT,gisadmin,2023-04-29,334.773884,1.0
23,24.0,0581800 2,1.0,6794.0,NaN,NaN,0.0,NaN,11th Ave - 18th St To 19th St,NaN,...,3.0,0.0,20.0,2105.0,NaN,NaT,gisadmin,2022-11-11,378.501571,2.0
24,25.0,2743300,1.0,NaN,NaN,NaN,0.0,NaN,Syringa Dr - W Shiloh Dr To NEOR,NaN,...,2.0,0.0,25.0,2754.0,NaN,NaT,gisadmin,2023-04-22,243.208237,1.0
25,26.0,1041700,1.0,4306.0,NaN,NaN,0.0,NaN,21st St - 17th Ave To 18th Ave,NaN,...,2.0,0.0,35.0,2432.0,NaN,NaT,gisadmin,2023-04-13,377.029825,2.0
26,27.0,1040900 2,1.0,4888.0,NaN,NaN,0.0,NaN,21st St - 9th Ave To 10th Ave,NaN,...,2.0,0.0,35.0,2065.0,NaN,NaT,gisadmin,2023-04-06,248.770927,2.0
27,28.0,0760800,1.0,NaN,NaN,NaN,0.0,NaN,14th Ave - 8th St To 9th St,NaN,...,2.0,0.0,20.0,2203.0,NaN,NaT,gisadmin,2023-04-23,338.577610,1.0
28,29.0,1041200,1.0,4890.0,NaN,NaN,0.0,NaN,21st St - 12th Ave To 13th Ave,NaN,...,2.0,0.0,35.0,2191.0,NaN,NaT,gisadmin,2023-04-13,385.434323,2.0
29,30.0,0581000 1,1.0,7694.0,NaN,NaN,0.0,NaN,11th Ave -10th St To 10th St,NaN,...,3.0,0.0,25.0,3738.0,NaN,NaT,gisadmin,2022-11-11,126.754019,2.0

In [128]:
print(df.at[2396, "Descriptio"])

ALLEY-3rd/4th Sts &8th/9th  Aves

In [ ]:
temp = []
for i in df.index:
    temp.append(df.at[i, 'Descriptio'])
    if pd.isna(temp[i]):
        continue
    sL = temp[i].find("To")
    if sL == -1:
        sL = temp[i].find("to")
        df.at[i, 'To'] = temp[i][sL+2:]
    df.at[i, 'To'] = temp[i][sL+2:]

    print(i,df.at[i, "From"])

In [ ]:
temp = []
for i in df.index:
    temp.append(df.at[i, 'Descriptio'])
    if pd.isna(temp[i]):
        continue
    sL = temp[i].find("/")
    if sL == -1:
        sL = temp[i].find("to")
        df.at[i, 'To'] = temp[i][sL+2:]
    df.at[i, 'To'] = temp[i][sL+2:]

    print(i,df.at[i, "From"])